apiVersion: v1
kind: Namespace
metadata:
  name: getdeck

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: beiboot-operator
  namespace: getdeck

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: getdeck:beiboot:operator
rules:
- apiGroups:
  - kopf.dev
  resources:
  - clusterkopfpeerings
  verbs:
  - list
  - watch
  - patch
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - patch
  - delete
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - create
  - patch
- apiGroups:
  - ''
  - apps
  - batch
  - extensions
  - events.k8s.io
  - rbac.authorization.k8s.io
  resources:
  - namespaces
  - roles
  - serviceaccounts
  - rolebindings
  - nodes
  - configmaps
  - secrets
  - deployments
  - statefulsets
  - services
  - pods
  - pods/exec
  - events
  verbs:
  - '*'
- apiGroups:
  - getdeck.dev
  resources:
  - beiboots
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: getdeck-beiboot-operator
  namespace: getdeck
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: getdeck:beiboot:operator
subjects:
- kind: ServiceAccount
  name: beiboot-operator
  namespace: getdeck

---
apiVersion: v1
kind: Service
metadata:
  name: beiboot-admission
  namespace: getdeck
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app: beiboot-operator

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: beiboot.getdeck.dev
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    caBundle: |
      LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZDakNDQXZLZ0F3SUJBZ0lVTzJZMlJqUVdL
      Vi9yTkJpOUx5Ry9xVWFqWENBd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tERW1NQ1FHQTFVRUF3d2RZ
      bVZwWW05dmRDMWhaRzFwYzNOcGIyNHVaMlYwWkdWamF5NXpkbU13SGhjTgpNakl4TVRFNE1qRXlO
      elUyV2hjTk1qTXhNVEU0TWpFeU56VTJXakFvTVNZd0pBWURWUVFEREIxaVpXbGliMjkwCkxXRmti
      V2x6YzJsdmJpNW5aWFJrWldOckxuTjJZekNDQWlJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dJUEFE
      Q0MKQWdvQ2dnSUJBTFd6OWc1dDdkbVN4dm9ob1hvSHRnQWsvdEpiOTlKLzNoekdzSGgwWExYbTBs
      bXJ3LzAvUjd4dworcXJPajdreUZ4R1NUREY0MGRmNyt5S3VTdkZxNGhpQjlqaFppakNTOFF4SFZ1
      TFVtMGNydjZGYWtKVmNVVW1DClZvRmkvNlJCVktLS0p4TzlRUU1YMWtaeUNXaW1wblN6d2Y0NDM5
      d0U0ZTJVcXBpWXl6Q2ZNZmlzQWVLRDE1dnQKYmRvM0NFYTVhc2tRTnFvZ0xYUWNxL0pkOTROYzN2
      Q2lVbGxUVXRJZkovb0VxS05tbmFqaHBRTVEwZ1plY0dESwo0SnZhcnNSd3I3N0RKUWllUWJsRi9w
      aW0xcjQ2UGQzQk1DSHVMUVNrdERxdTNFK1BHZkNLZC95SmhKQVhUTmorClZqdGxUZGYxZm5MS0hM
      U1Qyck9MK3lzZVR1WnA4eGtEQnZNcmlCajg0RDVZeEVQNUIwZm9rVTM2UUZJMkdydFcKNjFPZjNN
      N1l4V3dFbHBhYUJnRFk5MDQvNU5TcE5WVFJBYVdZZHZDUmdnOC91Qmw2NXR1MGQ3d21jamlRK1Fm
      ZQptRHhQczN0T29QMUZOcnYwUDk2dnRSVE55WGNVSXNUaWl4eDdQSjBkUnlINGdQdy92ZFluUElh
      RWFXOEpQaWI2CllVaVJHeFFWaXZLaDJ1NW1QaHlodzRxT3VNVHU5c1pIYjc4cEtpMGtsRko1TDNX
      WlNRUmFIUUZwRitVQncyclgKVDgzZjAxaDZXMlY3dm00TVNtRzBqcEYwdDM3cU1WUmNxVXpjeTFt
      UUVKVFFrck0rSVd1cGQ5V2d0cmhHc2M5RApvUXpGSTFIRm5mTGVMVXVUeVkrOVpNR25PcGlKVnNk
      MDNjMzJ0ay95SVcrbUZOTE8xbnJCQWdNQkFBR2pMREFxCk1DZ0dBMVVkRVFRaE1CK0NIV0psYVdK
      dmIzUXRZV1J0YVhOemFXOXVMbWRsZEdSbFkyc3VjM1pqTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJ
      Q0FRQ2JxQWJOT0hlUmdwbTloVmVSSDIxVHg1c2hmbEpzOU0vQy9iMDV2TUFWQjZiRgpBRktyNndT
      RDcwMk1yWFd4SG00SlZBY01xZVFvODlzb2J1S0FtUWd5WTdNdlllSnJHWjBrT0htZzRKZVcxTnFU
      CmhQUGRqNXdaZ05WcHg0dXl5NG9NK05pVW5CTndVS0diK2F0MGwxSmVLWUlwR1lySmtSQlo0ZmRk
      WlFvYU0yY1gKUmM1OWxCSisraVA2SnBuNGdKR2l2UEZwOGdTczFkanBUTWRWU3VJelJkbzlmNU81
      NEt6WnJ0di9ITzM5aVB6QQpSWnVNYlFzOU0zUDZObkQ0c3JSTjlQcG1KUXpuM1RSYlFUeDBoRkpw
      TmN0L1FkKzUyRzM1Tk81Zy9tVUk5aHowCjNRSy9rMlVSMUtMZ24ycURjMk4zanhjT1R2YURDbEVZ
      SDFnOVlMTnVuMU4rVzdLeUNwUzNlazhkZkgzeTRLNVQKZnUrT01VQjFRaDJJbWV3RzJTVnpFTmRE
      YjFxenMxellhYXlGVmFsalJEeW5MclJrTlUzWEo2WTlkMlM3NmllbApvZWtiT1N5RGtRdThHUllx
      QzNGckVROUN3STd5RFp1RnVoZnZGWTdrNzcvL3VuVDRHTDBOL0ZHa0JuZCtzUDFjCkxXbG9tVHB2
      Y0NzM0JHbFNkVjVWQkJ1YjdDWk0zdkVBRkoyb1RjUXBEN1R1VFNlNE5PdUVMbkJYZG5HR0lUVUUK
      S044dWNQdGlZcDF1bDZwSGI3U0VWRVdSNVMvdkw4Q2pFcmFqS0ZTQWIySDExTUFmMU1CcEZvZm9v
      UkZJdFNyVQpFNVM2R0dybG15elluRG5OektVNG52b3BlUU1maVNQaHd4M3N2dnZJaEVFU3Z6aVVw
      V2QxcDVRNGlCUXFoZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: beiboot-admission
      namespace: getdeck
      path: /validate-parameters
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: validate-parameters.beiboot.getdeck.dev
  namespaceSelector: {}
  objectSelector: {}
  rules:
  - apiGroups:
    - getdeck.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - beiboots
    scope: '*'
  sideEffects: None
  timeoutSeconds: 30

---
apiVersion: v1
data:
  clusterReadyTimeout: '180'
  gefyra: '{"enabled": true, "endpoint": null}'
  k8sVersion: 'null'
  maxLifetime: 'null'
  maxSessionTimeout: 'null'
  namespacePrefix: getdeck-bbt
  nodeLabels: '{"app": "beiboot", "beiboot.getdeck.dev/is-node": "true"}'
  nodeResources: '{"requests": {"cpu": "1", "memory": "1Gi"}, "limits": {}}'
  nodeStorageRequests: 1Gi
  nodes: '1'
  ports: 'null'
  serverLabels: '{"app": "beiboot", "beiboot.getdeck.dev/is-node": "true", "beiboot.getdeck.dev/is-server":
    "true"}'
  serverResources: '{"requests": {"cpu": "1", "memory": "1Gi"}, "limits": {}}'
  serverStartupTimeout: '60'
  serverStorageRequests: 1Gi
  shelfStorageClass: standard-rwo
  storageClass: standard-rwo
  tunnel: '{"enabled": true, "endpoint": null}'
kind: ConfigMap
metadata:
  name: beiboot-config
  namespace: getdeck

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: beiboot-operator
  name: beiboot-operator
  namespace: getdeck
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beiboot-operator
  template:
    metadata:
      labels:
        app: beiboot-operator
    spec:
      containers:
      - image: quay.io/getdeck/beiboot:1.3.1
        imagePullPolicy: Always
        name: beiboot
        ports:
        - containerPort: 9443
      serviceAccountName: beiboot-operator

